import type { Category } from "./types"

export const categories: Category[] = [
  {
    id: "trending",
    name: "Trending Now",
    videos: [
      {
        id: "v1",
        title: "Morning Routine Transition",
        description: "Smooth transition for morning routine videos",
        thumbnail: "/vibrant-morning-start.png",
        previewUrl: "/cozy-morning-prep.png",
        downloadUrl: "#",
        duration: "0:15",
        category: "transitions",
        tags: ["morning", "routine", "transition"],
        vimeoId: "1075439121",
      },
      {
        id: "v2",
        title: "Productivity Timer",
        description: "Animated productivity timer for focus videos",
        thumbnail: "/focused-work-session.png",
        previewUrl: "/focused-work-session.png",
        downloadUrl: "#",
        duration: "0:30",
        category: "elements",
        tags: ["productivity", "timer", "focus"],
        vimeoId: "1075439121",
      },
      {
        id: "v3",
        title: "Workout Transition",
        description: "Dynamic transition for fitness content",
        thumbnail: "/dynamic-workout-flow.png",
        previewUrl: "/dynamic-fitness-flow.png",
        downloadUrl: "#",
        duration: "0:10",
        category: "transitions",
        tags: ["fitness", "workout", "transition"],
        vimeoId: "1075439121",
      },
      {
        id: "v4",
        title: "Social Media Call-to-Action",
        description: "Animated social media CTA for video endings",
        thumbnail: "/vibrant-social-cta.png",
        previewUrl: "/vibrant-social-cta.png",
        downloadUrl: "#",
        duration: "0:20",
        category: "elements",
        tags: ["social", "cta", "ending"],
        vimeoId: "1075439121",
      },
      {
        id: "v5",
        title: "Recipe Intro",
        description: "Clean intro for recipe and cooking videos",
        thumbnail: "/vibrant-salad-intro.png",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=recipe intro video",
        downloadUrl: "#",
        duration: "0:12",
        category: "intros",
        tags: ["cooking", "recipe", "intro"],
        vimeoId: "1075439121",
      },
      {
        id: "v6",
        title: "Tech Review Transition",
        description: "Sleek transition for tech review videos",
        thumbnail: "/placeholder.svg?height=720&width=1280&query=tech review transition thumbnail",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=tech review transition video",
        downloadUrl: "#",
        duration: "0:08",
        category: "transitions",
        tags: ["tech", "review", "transition"],
        vimeoId: "1075439121",
      },
    ],
  },
  {
    id: "transitions",
    name: "Smooth Transitions",
    videos: [
      {
        id: "t1",
        title: "Slide Transition Pack",
        description: "Collection of smooth slide transitions",
        thumbnail: "/placeholder.svg?height=720&width=1280&query=slide transition thumbnail",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=slide transition video",
        downloadUrl: "#",
        duration: "0:45",
        category: "transitions",
        tags: ["slide", "transition", "pack"],
        vimeoId: "1075439121",
      },
      {
        id: "t2",
        title: "Zoom Transition",
        description: "Dynamic zoom in/out transition",
        thumbnail: "/placeholder.svg?height=720&width=1280&query=zoom transition thumbnail",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=zoom transition video",
        downloadUrl: "#",
        duration: "0:12",
        category: "transitions",
        tags: ["zoom", "transition"],
        vimeoId: "1075439121",
      },
      {
        id: "t3",
        title: "Glitch Effect Transition",
        description: "Modern glitch effect for transitions",
        thumbnail: "/placeholder.svg?height=720&width=1280&query=glitch effect thumbnail",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=glitch effect video",
        downloadUrl: "#",
        duration: "0:10",
        category: "transitions",
        tags: ["glitch", "effect", "transition"],
        vimeoId: "1075439121",
      },
      {
        id: "t4",
        title: "Smooth Wipe Transition",
        description: "Clean wipe transitions for professional videos",
        thumbnail: "/placeholder.svg?height=720&width=1280&query=wipe transition thumbnail",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=wipe transition video",
        downloadUrl: "#",
        duration: "0:15",
        category: "transitions",
        tags: ["wipe", "smooth", "transition"],
        vimeoId: "1075439121",
      },
      {
        id: "t5",
        title: "Spin Transition",
        description: "Rotating spin transition effect",
        thumbnail: "/placeholder.svg?height=720&width=1280&query=spin transition thumbnail",
        previewUrl: "/placeholder.svg?height=720&width=1280&query=spin transition video",
        downloadUrl: "#",
        duration: "0:08",
        category: "transitions",
        tags: ["spin", "rotate", "transition"],
        vimeoId: "1075439121",
      },
    ],
  },
  // Other categories remain the same...
]
