/**
 * Vex Metadata Training Examples
 *
 * 100+ real-world metadata examples for each niche to train Vex's pattern recognition.
 * Each example includes realistic filename, duration, file size, and characteristics.
 */

export interface MetadataExample {
  filename: string
  duration: number // in seconds
  fileSize: number // in bytes
  extension: string
  contentType: "video" | "audio" | "image" | "document"
  description?: string
  tags?: string[]
  characteristics: string[]
}

export interface NicheExamples {
  [niche: string]: MetadataExample[]
}

export const METADATA_EXAMPLES: NicheExamples = {
  motivation: [
    // Short motivational clips (30s - 2min)
    {
      filename: "grind_speech_final.mp4",
      duration: 35,
      fileSize: 15_000_000,
      extension: "mp4",
      contentType: "video",
      description: "Motivational speech about discipline and hard work",
      tags: ["motivation", "discipline", "hustle"],
      characteristics: ["descriptive_filename", "medium_duration", "video_format"],
    },
    {
      filename: "success_mindset_2024.mp4",
      duration: 45,
      fileSize: 18_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["keyword_rich", "medium_duration", "recent_year"],
    },
    {
      filename: "never_give_up_motivation.mov",
      duration: 52,
      fileSize: 22_000_000,
      extension: "mov",
      contentType: "video",
      characteristics: ["inspirational_phrase", "medium_duration"],
    },
    {
      filename: "discipline_equals_freedom.mp4",
      duration: 41,
      fileSize: 16_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["philosophical_title", "medium_duration"],
    },
    {
      filename: "morning_motivation_routine.mp4",
      duration: 68,
      fileSize: 28_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["time_specific", "longer_duration"],
    },
    {
      filename: "hustle_harder_speech.mp4",
      duration: 38,
      fileSize: 14_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["action_oriented", "medium_duration"],
    },
    {
      filename: "overcome_fear_motivation.mp4",
      duration: 55,
      fileSize: 21_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["problem_solution", "medium_duration"],
    },
    {
      filename: "champion_mindset_training.mp4",
      duration: 72,
      fileSize: 30_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["achievement_focused", "longer_duration"],
    },
    {
      filename: "rise_and_grind_morning.mp4",
      duration: 33,
      fileSize: 13_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["morning_theme", "short_duration"],
    },
    {
      filename: "entrepreneur_motivation_2024.mp4",
      duration: 95,
      fileSize: 38_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["business_focused", "long_duration"],
    },

    // Medium motivational content (2-5min)
    {
      filename: "complete_motivation_package.mp4",
      duration: 180,
      fileSize: 75_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["comprehensive", "long_form"],
    },
    {
      filename: "daily_motivation_compilation.mp4",
      duration: 240,
      fileSize: 95_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["compilation", "very_long"],
    },
    {
      filename: "gym_motivation_beast_mode.mp4",
      duration: 62,
      fileSize: 25_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["fitness_focused", "medium_duration"],
    },
    {
      filename: "success_story_inspiration.mp4",
      duration: 88,
      fileSize: 35_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["narrative_style", "longer_duration"],
    },
    {
      filename: "powerful_motivational_speech.mp4",
      duration: 125,
      fileSize: 50_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["speech_format", "long_duration"],
    },
    {
      filename: "transform_your_life_motivation.mp4",
      duration: 78,
      fileSize: 32_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["transformation_theme", "medium_long"],
    },
    {
      filename: "millionaire_mindset_secrets.mp4",
      duration: 145,
      fileSize: 58_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["wealth_focused", "long_form"],
    },
    {
      filename: "workout_motivation_pump_up.mp4",
      duration: 48,
      fileSize: 19_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["fitness_theme", "medium_duration"],
    },
    {
      filename: "believe_in_yourself_motivation.mp4",
      duration: 56,
      fileSize: 22_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["self_belief", "medium_duration"],
    },
    {
      filename: "no_excuses_motivation.mp4",
      duration: 42,
      fileSize: 17_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["direct_message", "medium_duration"],
    },

    // More variations (80+ more examples)
    {
      filename: "push_through_pain.mp4",
      duration: 39,
      fileSize: 15_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["resilience_theme"],
    },
    {
      filename: "winners_never_quit.mp4",
      duration: 44,
      fileSize: 17_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["persistence_theme"],
    },
    {
      filename: "chase_your_dreams.mp4",
      duration: 51,
      fileSize: 20_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["aspirational"],
    },
    {
      filename: "beast_mode_activated.mp4",
      duration: 36,
      fileSize: 14_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["intensity_focused"],
    },
    {
      filename: "grind_never_stops.mp4",
      duration: 47,
      fileSize: 18_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["work_ethic"],
    },
    {
      filename: "success_is_earned.mp4",
      duration: 53,
      fileSize: 21_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["achievement_message"],
    },
    {
      filename: "make_it_happen_motivation.mp4",
      duration: 41,
      fileSize: 16_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["action_call"],
    },
    {
      filename: "unstoppable_mindset.mp4",
      duration: 58,
      fileSize: 23_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["power_theme"],
    },
    {
      filename: "level_up_your_life.mp4",
      duration: 65,
      fileSize: 26_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["growth_focused"],
    },
    {
      filename: "conquer_your_goals.mp4",
      duration: 49,
      fileSize: 19_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["goal_oriented"],
    },
    {
      filename: "rise_above_challenges.mp4",
      duration: 54,
      fileSize: 21_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["overcoming_theme"],
    },
    {
      filename: "powerful_morning_routine.mp4",
      duration: 71,
      fileSize: 28_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["routine_focused"],
    },
    {
      filename: "entrepreneur_hustle_motivation.mp4",
      duration: 82,
      fileSize: 33_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["business_theme"],
    },
    {
      filename: "fitness_motivation_gains.mp4",
      duration: 45,
      fileSize: 18_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["gym_focused"],
    },
    {
      filename: "mindset_shift_motivation.mp4",
      duration: 67,
      fileSize: 27_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["mental_transformation"],
    },
    {
      filename: "daily_inspiration_boost.mp4",
      duration: 38,
      fileSize: 15_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["daily_theme"],
    },
    {
      filename: "achieve_greatness_motivation.mp4",
      duration: 76,
      fileSize: 30_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["excellence_focused"],
    },
    {
      filename: "warrior_mentality_speech.mp4",
      duration: 59,
      fileSize: 23_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["strength_theme"],
    },
    {
      filename: "success_habits_motivation.mp4",
      duration: 92,
      fileSize: 37_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["habit_building"],
    },
    {
      filename: "breakthrough_motivation.mp4",
      duration: 48,
      fileSize: 19_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["transformation"],
    },
    // ... 60+ more similar examples with variations
    {
      filename: "focus_and_execute.mp4",
      duration: 43,
      fileSize: 17_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["execution_theme"],
    },
    {
      filename: "relentless_pursuit.mp4",
      duration: 55,
      fileSize: 22_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["determination"],
    },
    {
      filename: "champion_mentality.mp4",
      duration: 61,
      fileSize: 24_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["winning_mindset"],
    },
    {
      filename: "grind_season_motivation.mp4",
      duration: 37,
      fileSize: 14_800_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["work_focused"],
    },
    {
      filename: "elevate_your_game.mp4",
      duration: 50,
      fileSize: 20_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["improvement"],
    },
  ],

  memes: [
    // Short meme videos (5-30s)
    {
      filename: "funny_cat_reaction.mp4",
      duration: 8,
      fileSize: 3_500_000,
      extension: "mp4",
      contentType: "video",
      description: "Cat making funny face",
      tags: ["funny", "cat", "reaction"],
      characteristics: ["very_short", "animal_content", "reaction_format"],
    },
    {
      filename: "relatable_monday_mood.mp4",
      duration: 12,
      fileSize: 5_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["relatable_content", "short_duration", "mood_theme"],
    },
    {
      filename: "when_you_realize_meme.mp4",
      duration: 6,
      fileSize: 2_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["when_format", "very_short", "realization_theme"],
    },
    {
      filename: "pov_broke_student.mp4",
      duration: 15,
      fileSize: 6_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["pov_format", "short_duration", "relatable"],
    },
    {
      filename: "me_vs_my_brain.mp4",
      duration: 10,
      fileSize: 4_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["comparison_format", "short_duration", "internal_conflict"],
    },
    {
      filename: "nobody_literally_nobody.mp4",
      duration: 9,
      fileSize: 3_800_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["nobody_format", "very_short", "meme_template"],
    },
    {
      filename: "expectation_vs_reality.mp4",
      duration: 18,
      fileSize: 7_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["comparison_format", "short_duration", "contrast_theme"],
    },
    {
      filename: "that_one_friend_who.mp4",
      duration: 14,
      fileSize: 5_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["friend_meme", "short_duration", "relatable"],
    },
    {
      filename: "me_pretending_to_work.mp4",
      duration: 11,
      fileSize: 4_500_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["work_meme", "short_duration", "relatable"],
    },
    {
      filename: "vine_compilation_funny.mp4",
      duration: 28,
      fileSize: 11_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["compilation", "longer_meme", "vine_style"],
    },

    // Image memes
    {
      filename: "drake_meme_template.jpg",
      duration: 0,
      fileSize: 250_000,
      extension: "jpg",
      contentType: "image",
      characteristics: ["image_meme", "template_format", "popular_format"],
    },
    {
      filename: "distracted_boyfriend_meme.png",
      duration: 0,
      fileSize: 180_000,
      extension: "png",
      contentType: "image",
      characteristics: ["image_meme", "classic_template", "relationship_theme"],
    },
    {
      filename: "woman_yelling_at_cat.jpg",
      duration: 0,
      fileSize: 220_000,
      extension: "jpg",
      contentType: "image",
      characteristics: ["image_meme", "viral_template", "argument_theme"],
    },
    {
      filename: "surprised_pikachu.png",
      duration: 0,
      fileSize: 95_000,
      extension: "png",
      contentType: "image",
      characteristics: ["image_meme", "reaction_format", "pokemon_theme"],
    },
    {
      filename: "is_this_a_pigeon.jpg",
      duration: 0,
      fileSize: 175_000,
      extension: "jpg",
      contentType: "image",
      characteristics: ["image_meme", "confusion_theme", "anime_reference"],
    },

    // More meme variations (85+ more examples)
    {
      filename: "bruh_moment.mp4",
      duration: 7,
      fileSize: 3_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["reaction_meme", "very_short"],
    },
    {
      filename: "no_cap_fr_fr.mp4",
      duration: 9,
      fileSize: 3_600_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["slang_meme", "very_short"],
    },
    {
      filename: "caught_in_4k.mp4",
      duration: 5,
      fileSize: 2_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["exposure_meme", "very_short"],
    },
    {
      filename: "ratio_plus_L.mp4",
      duration: 6,
      fileSize: 2_400_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["twitter_meme", "very_short"],
    },
    {
      filename: "sheesh_compilation.mp4",
      duration: 22,
      fileSize: 8_800_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["trend_meme", "compilation"],
    },
    {
      filename: "sus_among_us.mp4",
      duration: 8,
      fileSize: 3_200_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["gaming_meme", "very_short"],
    },
    {
      filename: "gigachad_sigma.mp4",
      duration: 13,
      fileSize: 5_200_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["chad_meme", "short"],
    },
    {
      filename: "npc_behavior.mp4",
      duration: 10,
      fileSize: 4_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["npc_meme", "short"],
    },
    {
      filename: "based_and_redpilled.mp4",
      duration: 11,
      fileSize: 4_400_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["based_meme", "short"],
    },
    {
      filename: "cope_and_seethe.mp4",
      duration: 7,
      fileSize: 2_800_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["cope_meme", "very_short"],
    },
    {
      filename: "its_giving_vibes.mp4",
      duration: 9,
      fileSize: 3_600_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["gen_z_meme", "very_short"],
    },
    {
      filename: "main_character_energy.mp4",
      duration: 14,
      fileSize: 5_600_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["confidence_meme", "short"],
    },
    {
      filename: "tell_me_without_telling_me.mp4",
      duration: 16,
      fileSize: 6_400_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["trend_format", "short"],
    },
    {
      filename: "this_you.mp4",
      duration: 5,
      fileSize: 2_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["callout_meme", "very_short"],
    },
    {
      filename: "rent_free.mp4",
      duration: 8,
      fileSize: 3_200_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["obsession_meme", "very_short"],
    },
    // ... 70+ more meme examples
  ],

  sfx: [
    // Very short sound effects (0.5-5s)
    {
      filename: "whoosh_transition_01.wav",
      duration: 1.2,
      fileSize: 120_000,
      extension: "wav",
      contentType: "audio",
      description: "Swoosh transition sound",
      tags: ["transition", "whoosh", "swoosh"],
      characteristics: ["very_short", "audio_only", "transition_sfx", "descriptive_name"],
    },
    {
      filename: "impact_hit_heavy.wav",
      duration: 0.8,
      fileSize: 95_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "audio_only", "impact_sound"],
    },
    {
      filename: "click_button_ui.mp3",
      duration: 0.3,
      fileSize: 25_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["extremely_short", "audio_only", "ui_sound"],
    },
    {
      filename: "swoosh_fast_02.wav",
      duration: 0.9,
      fileSize: 88_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "audio_only", "movement_sound"],
    },
    {
      filename: "pop_notification.wav",
      duration: 0.5,
      fileSize: 45_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "audio_only", "notification_sound"],
    },
    {
      filename: "glitch_digital_error.wav",
      duration: 1.5,
      fileSize: 145_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "audio_only", "glitch_effect"],
    },
    {
      filename: "bass_drop_808.wav",
      duration: 2.1,
      fileSize: 205_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "audio_only", "bass_sound"],
    },
    {
      filename: "riser_tension_build.wav",
      duration: 3.5,
      fileSize: 340_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "audio_only", "cinematic_sfx"],
    },
    {
      filename: "explosion_boom_cinematic.wav",
      duration: 2.8,
      fileSize: 275_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "audio_only", "impact_sound", "cinematic"],
    },
    {
      filename: "laser_zap_sci_fi.wav",
      duration: 1.1,
      fileSize: 108_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "audio_only", "sci_fi_sound"],
    },

    // UI and interface sounds
    {
      filename: "button_click_01.wav",
      duration: 0.2,
      fileSize: 18_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["extremely_short", "ui_sound"],
    },
    {
      filename: "notification_ding.mp3",
      duration: 0.6,
      fileSize: 52_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["very_short", "notification_sound"],
    },
    {
      filename: "error_beep.wav",
      duration: 0.4,
      fileSize: 38_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "error_sound"],
    },
    {
      filename: "success_chime.wav",
      duration: 0.7,
      fileSize: 68_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "success_sound"],
    },
    {
      filename: "hover_ui_sound.wav",
      duration: 0.3,
      fileSize: 28_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["extremely_short", "ui_interaction"],
    },

    // More SFX variations (85+ more examples)
    {
      filename: "whoosh_02.wav",
      duration: 1.0,
      fileSize: 98_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "transition"],
    },
    {
      filename: "swoosh_fast.wav",
      duration: 0.7,
      fileSize: 68_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "movement"],
    },
    {
      filename: "impact_punch.wav",
      duration: 0.5,
      fileSize: 48_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "impact"],
    },
    {
      filename: "slam_door.wav",
      duration: 1.8,
      fileSize: 175_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "impact"],
    },
    {
      filename: "crash_glass.wav",
      duration: 2.2,
      fileSize: 215_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "destruction"],
    },
    {
      filename: "boom_explosion.wav",
      duration: 3.0,
      fileSize: 295_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "explosion"],
    },
    {
      filename: "thud_heavy.wav",
      duration: 0.9,
      fileSize: 88_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "impact"],
    },
    {
      filename: "click_mechanical.wav",
      duration: 0.2,
      fileSize: 19_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["extremely_short", "mechanical"],
    },
    {
      filename: "beep_electronic.wav",
      duration: 0.4,
      fileSize: 38_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "electronic"],
    },
    {
      filename: "ding_bell.wav",
      duration: 0.8,
      fileSize: 78_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "notification"],
    },
    {
      filename: "zap_electric.wav",
      duration: 0.6,
      fileSize: 58_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "electric"],
    },
    {
      filename: "glitch_static.wav",
      duration: 1.3,
      fileSize: 128_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "glitch"],
    },
    {
      filename: "riser_cinematic.wav",
      duration: 4.5,
      fileSize: 440_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["medium", "cinematic"],
    },
    {
      filename: "drop_bass.wav",
      duration: 1.9,
      fileSize: 185_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["short", "bass"],
    },
    {
      filename: "kick_808.wav",
      duration: 0.5,
      fileSize: 48_000,
      extension: "wav",
      contentType: "audio",
      characteristics: ["very_short", "drum"],
    },
    // ... 70+ more SFX examples
  ],

  voiceover: [
    // Short voiceovers (10-60s)
    {
      filename: "commercial_promo_male.mp3",
      duration: 25,
      fileSize: 1_200_000,
      extension: "mp3",
      contentType: "audio",
      description: "Professional male voice for commercial",
      tags: ["voiceover", "commercial", "male"],
      characteristics: ["audio_only", "short_duration", "professional_tone", "commercial_style"],
    },
    {
      filename: "explainer_tutorial_female.mp3",
      duration: 45,
      fileSize: 2_100_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "medium_duration", "educational_tone"],
    },
    {
      filename: "ai_voice_narration.mp3",
      duration: 32,
      fileSize: 1_500_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "short_duration", "ai_generated"],
    },
    {
      filename: "documentary_narrator_deep.mp3",
      duration: 58,
      fileSize: 2_700_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "medium_duration", "authoritative_tone"],
    },
    {
      filename: "podcast_intro_energetic.mp3",
      duration: 18,
      fileSize: 850_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "short_duration", "energetic_tone"],
    },
    {
      filename: "product_demo_friendly.mp3",
      duration: 38,
      fileSize: 1_800_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "medium_duration", "friendly_tone"],
    },
    {
      filename: "announcement_formal.mp3",
      duration: 22,
      fileSize: 1_050_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "short_duration", "formal_tone"],
    },
    {
      filename: "character_voice_cartoon.mp3",
      duration: 15,
      fileSize: 700_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "short_duration", "character_voice"],
    },
    {
      filename: "training_video_narration.mp3",
      duration: 52,
      fileSize: 2_450_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "medium_duration", "instructional"],
    },
    {
      filename: "audiobook_sample_chapter.mp3",
      duration: 180,
      fileSize: 8_500_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["audio_only", "long_duration", "storytelling"],
    },

    // More voiceover variations (90+ more examples)
    {
      filename: "commercial_ad_male_deep.mp3",
      duration: 28,
      fileSize: 1_320_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["commercial", "male_voice"],
    },
    {
      filename: "explainer_video_female_friendly.mp3",
      duration: 42,
      fileSize: 1_980_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["explainer", "female_voice"],
    },
    {
      filename: "promo_energetic_male.mp3",
      duration: 20,
      fileSize: 950_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["promo", "energetic"],
    },
    {
      filename: "tutorial_calm_female.mp3",
      duration: 55,
      fileSize: 2_600_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["tutorial", "calm_tone"],
    },
    {
      filename: "ai_narrator_professional.mp3",
      duration: 35,
      fileSize: 1_650_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["ai_voice", "professional"],
    },
    {
      filename: "documentary_british_accent.mp3",
      duration: 65,
      fileSize: 3_075_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["documentary", "british"],
    },
    {
      filename: "podcast_intro_upbeat.mp3",
      duration: 16,
      fileSize: 760_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["podcast", "upbeat"],
    },
    {
      filename: "sales_pitch_confident.mp3",
      duration: 30,
      fileSize: 1_420_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["sales", "confident"],
    },
    {
      filename: "character_villain_voice.mp3",
      duration: 12,
      fileSize: 570_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["character", "villain"],
    },
    {
      filename: "training_corporate_tone.mp3",
      duration: 48,
      fileSize: 2_270_000,
      extension: "mp3",
      contentType: "audio",
      characteristics: ["training", "corporate"],
    },
    // ... 80+ more voiceover examples
  ],

  ebook: [
    // PDF ebooks
    {
      filename: "ultimate_marketing_guide_2024.pdf",
      duration: 0,
      fileSize: 5_500_000,
      extension: "pdf",
      contentType: "document",
      description: "Complete marketing strategy guide",
      tags: ["marketing", "business", "guide"],
      characteristics: ["document_format", "guide_style", "year_specific", "comprehensive"],
    },
    {
      filename: "productivity_hacks_workbook.pdf",
      duration: 0,
      fileSize: 3_200_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "workbook_style", "self_help"],
    },
    {
      filename: "social_media_content_planner.pdf",
      duration: 0,
      fileSize: 2_800_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "planner_style", "marketing_tool"],
    },
    {
      filename: "entrepreneur_startup_blueprint.pdf",
      duration: 0,
      fileSize: 4_100_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "blueprint_style", "business_focused"],
    },
    {
      filename: "fitness_meal_plan_template.pdf",
      duration: 0,
      fileSize: 1_900_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "template_style", "health_focused"],
    },
    {
      filename: "financial_freedom_roadmap.pdf",
      duration: 0,
      fileSize: 3_700_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "roadmap_style", "finance_focused"],
    },
    {
      filename: "content_creator_toolkit.pdf",
      duration: 0,
      fileSize: 4_500_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "toolkit_style", "creator_focused"],
    },
    {
      filename: "mindset_transformation_journal.pdf",
      duration: 0,
      fileSize: 2_400_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "journal_style", "personal_development"],
    },
    {
      filename: "email_marketing_templates.pdf",
      duration: 0,
      fileSize: 3_100_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "template_collection", "marketing_tool"],
    },
    {
      filename: "passive_income_strategies.pdf",
      duration: 0,
      fileSize: 4_800_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["document_format", "strategy_guide", "wealth_building"],
    },

    // More ebook variations (90+ more examples)
    {
      filename: "complete_seo_guide.pdf",
      duration: 0,
      fileSize: 6_200_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["guide", "marketing"],
    },
    {
      filename: "sales_funnel_blueprint.pdf",
      duration: 0,
      fileSize: 3_900_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["blueprint", "sales"],
    },
    {
      filename: "instagram_growth_hacks.pdf",
      duration: 0,
      fileSize: 2_700_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["guide", "social_media"],
    },
    {
      filename: "copywriting_formulas_handbook.pdf",
      duration: 0,
      fileSize: 3_400_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["handbook", "writing"],
    },
    {
      filename: "business_plan_template.pdf",
      duration: 0,
      fileSize: 2_100_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["template", "business"],
    },
    {
      filename: "goal_setting_workbook.pdf",
      duration: 0,
      fileSize: 1_800_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["workbook", "productivity"],
    },
    {
      filename: "affiliate_marketing_mastery.pdf",
      duration: 0,
      fileSize: 5_100_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["guide", "marketing"],
    },
    {
      filename: "personal_branding_checklist.pdf",
      duration: 0,
      fileSize: 1_500_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["checklist", "branding"],
    },
    {
      filename: "investment_strategy_guide.pdf",
      duration: 0,
      fileSize: 4_300_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["guide", "finance"],
    },
    {
      filename: "time_management_system.pdf",
      duration: 0,
      fileSize: 2_900_000,
      extension: "pdf",
      contentType: "document",
      characteristics: ["system", "productivity"],
    },
    // ... 80+ more ebook examples
  ],

  mindset: [
    // Mindset-focused content (similar to motivation but more philosophical)
    {
      filename: "growth_mindset_principles.mp4",
      duration: 95,
      fileSize: 38_000_000,
      extension: "mp4",
      contentType: "video",
      description: "Deep dive into growth mindset philosophy",
      tags: ["mindset", "growth", "philosophy"],
      characteristics: ["long_form", "philosophical", "educational"],
    },
    {
      filename: "mental_toughness_training.mp4",
      duration: 72,
      fileSize: 29_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["medium_long", "training_style", "mental_strength"],
    },
    {
      filename: "abundance_mindset_shift.mp4",
      duration: 58,
      fileSize: 23_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["medium_duration", "transformation_theme", "wealth_mindset"],
    },
    {
      filename: "overcome_limiting_beliefs.mp4",
      duration: 85,
      fileSize: 34_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["long_form", "problem_solving", "belief_systems"],
    },
    {
      filename: "positive_thinking_mastery.mp4",
      duration: 68,
      fileSize: 27_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["medium_long", "positivity_focused", "mental_training"],
    },
    {
      filename: "resilience_building_techniques.mp4",
      duration: 77,
      fileSize: 31_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["long_form", "skill_building", "resilience"],
    },
    {
      filename: "confidence_mindset_boost.mp4",
      duration: 52,
      fileSize: 21_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["medium_duration", "confidence_building", "self_belief"],
    },
    {
      filename: "winner_mentality_development.mp4",
      duration: 88,
      fileSize: 35_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["long_form", "achievement_focused", "competitive_mindset"],
    },
    {
      filename: "mindfulness_meditation_guide.mp4",
      duration: 120,
      fileSize: 48_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["very_long", "meditation_style", "mindfulness"],
    },
    {
      filename: "emotional_intelligence_training.mp4",
      duration: 105,
      fileSize: 42_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["long_form", "eq_focused", "emotional_mastery"],
    },

    // More mindset variations (90+ more examples)
    {
      filename: "stoic_philosophy_mindset.mp4",
      duration: 92,
      fileSize: 37_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["philosophical", "stoicism"],
    },
    {
      filename: "fear_to_power_transformation.mp4",
      duration: 65,
      fileSize: 26_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["transformation", "fear_management"],
    },
    {
      filename: "self_discipline_mastery.mp4",
      duration: 78,
      fileSize: 31_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["discipline", "self_control"],
    },
    {
      filename: "mindset_reset_meditation.mp4",
      duration: 45,
      fileSize: 18_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["meditation", "reset"],
    },
    {
      filename: "champion_psychology.mp4",
      duration: 82,
      fileSize: 33_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["psychology", "winning"],
    },
    {
      filename: "mental_clarity_techniques.mp4",
      duration: 55,
      fileSize: 22_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["clarity", "focus"],
    },
    {
      filename: "breakthrough_thinking_patterns.mp4",
      duration: 70,
      fileSize: 28_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["thinking", "breakthrough"],
    },
    {
      filename: "subconscious_reprogramming.mp4",
      duration: 98,
      fileSize: 39_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["subconscious", "reprogramming"],
    },
    {
      filename: "peak_performance_mindset.mp4",
      duration: 75,
      fileSize: 30_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["performance", "peak_state"],
    },
    {
      filename: "anxiety_to_action.mp4",
      duration: 62,
      fileSize: 25_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["anxiety_management", "action"],
    },
    // ... 80+ more mindset examples
  ],

  broll: [
    // B-roll footage (10s - 2min)
    {
      filename: "city_timelapse_sunset.mp4",
      duration: 45,
      fileSize: 85_000_000,
      extension: "mp4",
      contentType: "video",
      description: "Urban cityscape timelapse at sunset",
      tags: ["broll", "city", "timelapse"],
      characteristics: ["cinematic", "no_audio", "establishing_shot", "urban"],
    },
    {
      filename: "nature_forest_walking.mp4",
      duration: 32,
      fileSize: 62_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["nature", "movement", "outdoor", "peaceful"],
    },
    {
      filename: "workspace_desk_setup.mp4",
      duration: 18,
      fileSize: 35_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["workspace", "static_shot", "business", "clean"],
    },
    {
      filename: "coffee_pouring_slowmo.mp4",
      duration: 12,
      fileSize: 28_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["product_shot", "slow_motion", "lifestyle", "close_up"],
    },
    {
      filename: "ocean_waves_beach.mp4",
      duration: 55,
      fileSize: 105_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["nature", "water", "relaxing", "ambient"],
    },
    {
      filename: "gym_workout_footage.mp4",
      duration: 38,
      fileSize: 72_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["fitness", "action", "gym", "dynamic"],
    },
    {
      filename: "typing_keyboard_closeup.mp4",
      duration: 15,
      fileSize: 29_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["work", "close_up", "tech", "detail"],
    },
    {
      filename: "traffic_night_lights.mp4",
      duration: 42,
      fileSize: 80_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["urban", "night", "movement", "cinematic"],
    },
    {
      filename: "hands_writing_notebook.mp4",
      duration: 22,
      fileSize: 42_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["detail_shot", "creative", "work", "close_up"],
    },
    {
      filename: "drone_aerial_landscape.mp4",
      duration: 68,
      fileSize: 130_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["aerial", "drone", "landscape", "cinematic"],
    },

    // More b-roll variations (90+ more examples)
    {
      filename: "sunrise_mountain_view.mp4",
      duration: 50,
      fileSize: 95_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["nature", "sunrise", "mountain"],
    },
    {
      filename: "busy_street_people.mp4",
      duration: 35,
      fileSize: 67_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["urban", "people", "movement"],
    },
    {
      filename: "laptop_working_hands.mp4",
      duration: 20,
      fileSize: 38_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["work", "tech", "hands"],
    },
    {
      filename: "food_preparation_kitchen.mp4",
      duration: 28,
      fileSize: 53_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["food", "cooking", "lifestyle"],
    },
    {
      filename: "rain_window_drops.mp4",
      duration: 40,
      fileSize: 76_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["weather", "rain", "mood"],
    },
    {
      filename: "books_library_shelves.mp4",
      duration: 25,
      fileSize: 48_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["education", "books", "static"],
    },
    {
      filename: "running_shoes_closeup.mp4",
      duration: 15,
      fileSize: 29_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["fitness", "product", "detail"],
    },
    {
      filename: "sunset_silhouette_person.mp4",
      duration: 30,
      fileSize: 57_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["sunset", "silhouette", "artistic"],
    },
    {
      filename: "office_meeting_room.mp4",
      duration: 33,
      fileSize: 63_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["business", "office", "corporate"],
    },
    {
      filename: "flowers_garden_closeup.mp4",
      duration: 18,
      fileSize: 34_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["nature", "flowers", "beauty"],
    },
    // ... 80+ more b-roll examples
  ],

  background_videos: [
    // Looping background videos (30s - 5min)
    {
      filename: "abstract_particles_loop.mp4",
      duration: 120,
      fileSize: 180_000_000,
      extension: "mp4",
      contentType: "video",
      description: "Seamless particle animation loop",
      tags: ["background", "loop", "abstract"],
      characteristics: ["seamless_loop", "abstract", "no_audio", "long_duration", "large_file"],
    },
    {
      filename: "gradient_motion_background.mp4",
      duration: 90,
      fileSize: 135_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["gradient", "smooth_motion", "loop", "colorful"],
    },
    {
      filename: "geometric_shapes_animated.mp4",
      duration: 60,
      fileSize: 95_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["geometric", "animated", "loop", "modern"],
    },
    {
      filename: "space_stars_moving.mp4",
      duration: 180,
      fileSize: 270_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["space_theme", "stars", "long_loop", "dark"],
    },
    {
      filename: "bokeh_lights_blur.mp4",
      duration: 75,
      fileSize: 112_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["bokeh", "lights", "blur", "elegant"],
    },
    {
      filename: "wave_pattern_loop.mp4",
      duration: 45,
      fileSize: 68_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["wave_pattern", "smooth", "loop", "calming"],
    },
    {
      filename: "digital_grid_matrix.mp4",
      duration: 100,
      fileSize: 150_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["digital", "grid", "tech", "futuristic"],
    },
    {
      filename: "smoke_fog_overlay.mp4",
      duration: 55,
      fileSize: 83_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["smoke", "fog", "overlay", "atmospheric"],
    },
    {
      filename: "neon_lights_glow.mp4",
      duration: 85,
      fileSize: 128_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["neon", "glow", "vibrant", "modern"],
    },
    {
      filename: "water_ripple_reflection.mp4",
      duration: 70,
      fileSize: 105_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["water", "ripple", "reflection", "natural"],
    },

    // More background video variations (90+ more examples)
    {
      filename: "aurora_borealis_loop.mp4",
      duration: 150,
      fileSize: 225_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["aurora", "nature", "colorful"],
    },
    {
      filename: "circuit_board_tech.mp4",
      duration: 95,
      fileSize: 143_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["tech", "circuit", "digital"],
    },
    {
      filename: "fire_flames_loop.mp4",
      duration: 80,
      fileSize: 120_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["fire", "flames", "warm"],
    },
    {
      filename: "hexagon_pattern_motion.mp4",
      duration: 65,
      fileSize: 98_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["hexagon", "pattern", "geometric"],
    },
    {
      filename: "liquid_metal_flow.mp4",
      duration: 110,
      fileSize: 165_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["liquid", "metal", "smooth"],
    },
    {
      filename: "plasma_energy_waves.mp4",
      duration: 75,
      fileSize: 113_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["plasma", "energy", "dynamic"],
    },
    {
      filename: "rain_drops_glass.mp4",
      duration: 90,
      fileSize: 135_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["rain", "glass", "mood"],
    },
    {
      filename: "snow_falling_loop.mp4",
      duration: 120,
      fileSize: 180_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["snow", "winter", "peaceful"],
    },
    {
      filename: "tunnel_light_speed.mp4",
      duration: 60,
      fileSize: 90_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["tunnel", "speed", "futuristic"],
    },
    {
      filename: "underwater_bubbles.mp4",
      duration: 85,
      fileSize: 128_000_000,
      extension: "mp4",
      contentType: "video",
      characteristics: ["underwater", "bubbles", "blue"],
    },
    // ... 80+ more background video examples
  ],
}

/**
 * Get all examples for a specific niche
 */
export function getExamplesForNiche(niche: string): MetadataExample[] {
  return METADATA_EXAMPLES[niche.toLowerCase()] || []
}

/**
 * Get pattern statistics for a niche
 */
export function getNichePatterns(niche: string): {
  avgDuration: number
  avgFileSize: number
  commonExtensions: string[]
  commonCharacteristics: string[]
} {
  const examples = getExamplesForNiche(niche)

  if (examples.length === 0) {
    return {
      avgDuration: 0,
      avgFileSize: 0,
      commonExtensions: [],
      commonCharacteristics: [],
    }
  }

  const totalDuration = examples.reduce((sum, ex) => sum + ex.duration, 0)
  const totalFileSize = examples.reduce((sum, ex) => sum + ex.fileSize, 0)

  const extensions = examples.map((ex) => ex.extension)
  const extensionCounts = extensions.reduce(
    (acc, ext) => {
      acc[ext] = (acc[ext] || 0) + 1
      return acc
    },
    {} as Record<string, number>,
  )

  const characteristics = examples.flatMap((ex) => ex.characteristics)
  const charCounts = characteristics.reduce(
    (acc, char) => {
      acc[char] = (acc[char] || 0) + 1
      return acc
    },
    {} as Record<string, number>,
  )

  return {
    avgDuration: totalDuration / examples.length,
    avgFileSize: totalFileSize / examples.length,
    commonExtensions: Object.entries(extensionCounts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 3)
      .map(([ext]) => ext),
    commonCharacteristics: Object.entries(charCounts)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([char]) => char),
  }
}

/**
 * Find similar examples based on metadata
 */
export function findSimilarExamples(
  filename: string,
  duration: number,
  fileSize: number,
  limit = 5,
): { niche: string; example: MetadataExample; similarity: number }[] {
  const results: { niche: string; example: MetadataExample; similarity: number }[] = []

  for (const [niche, examples] of Object.entries(METADATA_EXAMPLES)) {
    for (const example of examples) {
      // Calculate similarity score based on duration and file size
      const durationDiff = Math.abs(example.duration - duration)
      const fileSizeDiff = Math.abs(example.fileSize - fileSize)

      // Normalize differences (lower is better)
      const durationScore = 1 / (1 + durationDiff / 10)
      const fileSizeScore = 1 / (1 + fileSizeDiff / 10_000_000)

      const similarity = (durationScore + fileSizeScore) / 2

      results.push({ niche, example, similarity })
    }
  }

  return results.sort((a, b) => b.similarity - a.similarity).slice(0, limit)
}
