/**
 * Vex Keyword Intelligence Database
 *
 * Comprehensive keyword system for content categorization across 5 major niches:
 * - Motivation
 * - Memes
 * - SFX (Sound Effects)
 * - AI Voiceovers
 * - Ebooks
 *
 * Each niche contains:
 * - Primary keywords (100+)
 * - Subtopics with category keywords
 * - Synonym groups for flexible matching
 */

export interface NicheKeywords {
  primary: string[]
  subtopics: {
    name: string
    keywords: string[]
  }[]
  synonyms: {
    group: string
    terms: string[]
  }[]
}

export interface KeywordDatabase {
  [niche: string]: NicheKeywords
}

export const KEYWORD_DATABASE: KeywordDatabase = {
  motivation: {
    primary: [
      // Success & Achievement
      "success",
      "achieve",
      "achievement",
      "goal",
      "goals",
      "ambition",
      "ambitious",
      "winner",
      "winning",
      "champion",
      "victory",
      "triumph",
      "conquer",
      "overcome",
      "breakthrough",
      "milestone",
      "progress",
      "growth",
      "improve",
      "excellence",
      "outstanding",
      "exceptional",
      "superior",
      "elite",
      "master",
      "mastery",
      "expert",
      "pro",

      // Mindset & Attitude
      "mindset",
      "attitude",
      "positive",
      "optimism",
      "confidence",
      "believe",
      "belief",
      "faith",
      "trust",
      "hope",
      "courage",
      "brave",
      "fearless",
      "bold",
      "determined",
      "determination",
      "persistence",
      "perseverance",
      "grit",
      "resilience",
      "resilient",
      "strong",
      "strength",
      "power",
      "powerful",
      "unstoppable",
      "unbreakable",

      // Action & Hustle
      "hustle",
      "grind",
      "work",
      "hardwork",
      "dedication",
      "committed",
      "commitment",
      "discipline",
      "focus",
      "focused",
      "driven",
      "motivated",
      "motivation",
      "inspire",
      "inspiration",
      "passion",
      "passionate",
      "energy",
      "energetic",
      "action",
      "execute",
      "execution",
      "productivity",
      "productive",
      "efficient",
      "effectiveness",

      // Business & Entrepreneurship
      "entrepreneur",
      "business",
      "startup",
      "founder",
      "ceo",
      "boss",
      "leader",
      "leadership",
      "vision",
      "visionary",
      "strategy",
      "strategic",
      "growth",
      "scale",
      "empire",
      "wealth",
      "rich",
      "money",
      "financial",
      "freedom",
      "millionaire",
      "billionaire",
      "invest",
      "investment",
      "profit",
      "revenue",
      "income",

      // Personal Development
      "transform",
      "transformation",
      "change",
      "evolve",
      "evolution",
      "upgrade",
      "level up",
      "next level",
      "better",
      "best",
      "improve",
      "improvement",
      "develop",
      "development",
      "learn",
      "learning",
      "knowledge",
      "wisdom",
      "smart",
      "intelligent",
      "genius",
      "potential",
      "capability",
      "skill",
      "talent",
      "ability",
      "performance",
    ],
    subtopics: [
      {
        name: "Morning Motivation",
        keywords: [
          "morning",
          "wake up",
          "rise",
          "sunrise",
          "dawn",
          "early",
          "start",
          "begin",
          "fresh start",
          "new day",
          "morning routine",
          "morning ritual",
          "breakfast",
          "coffee",
          "energize",
          "kickstart",
          "jumpstart",
          "activate",
        ],
      },
      {
        name: "Gym & Fitness",
        keywords: [
          "gym",
          "workout",
          "fitness",
          "exercise",
          "train",
          "training",
          "muscle",
          "strength",
          "bodybuilding",
          "lift",
          "weights",
          "cardio",
          "run",
          "running",
          "athlete",
          "athletic",
          "sport",
          "sports",
          "fit",
          "health",
          "healthy",
          "beast mode",
          "gains",
          "shredded",
          "ripped",
          "sweat",
          "grind",
          "push",
          "rep",
          "set",
        ],
      },
      {
        name: "Quotes & Wisdom",
        keywords: [
          "quote",
          "quotes",
          "wisdom",
          "wise",
          "saying",
          "proverb",
          "advice",
          "lesson",
          "teach",
          "teaching",
          "philosophy",
          "truth",
          "reality",
          "fact",
          "principle",
          "rule",
          "law",
          "mantra",
          "affirmation",
        ],
      },
      {
        name: "Overcoming Adversity",
        keywords: [
          "struggle",
          "challenge",
          "obstacle",
          "difficulty",
          "hardship",
          "adversity",
          "pain",
          "suffer",
          "failure",
          "fail",
          "defeat",
          "loss",
          "setback",
          "comeback",
          "rise",
          "recover",
          "bounce back",
          "never give up",
          "keep going",
          "persist",
          "endure",
          "survive",
          "warrior",
          "fighter",
          "battle",
          "fight",
        ],
      },
    ],
    synonyms: [
      {
        group: "success",
        terms: ["success", "achievement", "accomplishment", "victory", "triumph", "win", "winning"],
      },
      {
        group: "work_hard",
        terms: ["hustle", "grind", "work hard", "dedication", "commitment", "effort", "labor"],
      },
      {
        group: "mindset",
        terms: ["mindset", "mentality", "attitude", "perspective", "outlook", "thinking", "thought process"],
      },
      {
        group: "motivation",
        terms: ["motivation", "inspiration", "drive", "ambition", "determination", "willpower"],
      },
      {
        group: "improve",
        terms: ["improve", "better", "enhance", "upgrade", "level up", "progress", "advance", "develop"],
      },
      {
        group: "entrepreneur",
        terms: ["entrepreneur", "business owner", "founder", "startup", "ceo", "boss", "businessman"],
      },
      {
        group: "wealth",
        terms: ["wealth", "money", "rich", "financial freedom", "millionaire", "success", "prosperity"],
      },
      {
        group: "strong",
        terms: ["strong", "powerful", "mighty", "unstoppable", "unbreakable", "resilient", "tough"],
      },
      {
        group: "focus",
        terms: ["focus", "concentrate", "attention", "discipline", "dedication", "committed"],
      },
      {
        group: "goal",
        terms: ["goal", "target", "objective", "aim", "mission", "purpose", "vision", "dream"],
      },
    ],
  },

  memes: {
    primary: [
      // Meme Formats
      "meme",
      "template",
      "format",
      "trend",
      "trending",
      "viral",
      "funny",
      "humor",
      "comedy",
      "joke",
      "laugh",
      "lol",
      "lmao",
      "rofl",
      "hilarious",
      "savage",
      "roast",
      "burn",
      "dank",
      "cursed",
      "blessed",

      // Reactions & Emotions
      "reaction",
      "mood",
      "vibe",
      "energy",
      "feeling",
      "emotion",
      "face",
      "expression",
      "look",
      "stare",
      "cringe",
      "awkward",
      "embarrassing",
      "relatable",
      "relate",
      "same",
      "me irl",
      "literally me",

      // Internet Culture
      "internet",
      "online",
      "social media",
      "twitter",
      "tiktok",
      "instagram",
      "reddit",
      "discord",
      "twitch",
      "streamer",
      "content",
      "post",
      "share",
      "viral",
      "blow up",
      "trending",
      "popular",
      "famous",

      // Meme Characters & Formats
      "drake",
      "distracted boyfriend",
      "woman yelling",
      "cat",
      "dog",
      "doge",
      "pepe",
      "wojak",
      "chad",
      "virgin",
      "gigachad",
      "sigma",
      "alpha",
      "beta",
      "npc",
      "based",
      "cringe",
      "cope",
      "seethe",
      "ratio",

      // Situations & Scenarios
      "when",
      "that moment",
      "pov",
      "nobody",
      "everyone",
      "literally",
      "actually",
      "basically",
      "technically",
      "imagine",
      "be like",
      "meanwhile",
      "expectation",
      "reality",
      "before",
      "after",
      "vs",
      "versus",

      // Slang & Terms
      "bruh",
      "bro",
      "dude",
      "man",
      "fr",
      "no cap",
      "cap",
      "facts",
      "real",
      "true",
      "valid",
      "mood",
      "big mood",
      "vibe check",
      "sus",
      "sussy",
      "imposter",
      "among us",
      "sheesh",
      "bussin",
      "slaps",
      "hits different",
      "built different",
      "different breed",
      "goat",
      "legend",
      "icon",
      "king",
      "queen",
    ],
    subtopics: [
      {
        name: "Reaction Memes",
        keywords: [
          "reaction",
          "when",
          "me when",
          "my face when",
          "that face when",
          "pov",
          "mood",
          "relatable",
          "literally me",
          "same",
          "me irl",
          "accurate",
          "too real",
          "called out",
          "exposed",
          "caught",
        ],
      },
      {
        name: "Text Memes",
        keywords: [
          "text",
          "caption",
          "quote",
          "tweet",
          "post",
          "comment",
          "reply",
          "thread",
          "conversation",
          "chat",
          "message",
          "dm",
          "screenshot",
          "twitter",
          "tumblr",
          "reddit",
          "facebook",
        ],
      },
      {
        name: "Video Memes",
        keywords: [
          "video",
          "clip",
          "edit",
          "compilation",
          "montage",
          "tiktok",
          "vine",
          "youtube",
          "short",
          "reel",
          "story",
          "snap",
          "snapchat",
          "loop",
          "gif",
          "animation",
          "animated",
        ],
      },
      {
        name: "Gaming Memes",
        keywords: [
          "gaming",
          "gamer",
          "game",
          "video game",
          "pc",
          "console",
          "xbox",
          "playstation",
          "nintendo",
          "steam",
          "twitch",
          "streamer",
          "esports",
          "competitive",
          "noob",
          "pro",
          "tryhard",
          "casual",
          "rage",
          "rage quit",
          "gg",
          "ez",
          "rekt",
          "pwned",
          "owned",
        ],
      },
    ],
    synonyms: [
      {
        group: "funny",
        terms: ["funny", "hilarious", "comedy", "humor", "joke", "laugh", "lol", "lmao"],
      },
      {
        group: "meme",
        terms: ["meme", "template", "format", "trend", "viral"],
      },
      {
        group: "reaction",
        terms: ["reaction", "response", "mood", "vibe", "energy", "feeling"],
      },
      {
        group: "relatable",
        terms: ["relatable", "relate", "same", "me irl", "literally me", "accurate", "too real"],
      },
      {
        group: "cringe",
        terms: ["cringe", "awkward", "embarrassing", "uncomfortable", "yikes", "oof"],
      },
      {
        group: "savage",
        terms: ["savage", "roast", "burn", "destroyed", "murdered", "killed", "rekt"],
      },
      {
        group: "based",
        terms: ["based", "chad", "sigma", "alpha", "gigachad", "king"],
      },
      {
        group: "viral",
        terms: ["viral", "trending", "popular", "blow up", "famous", "everywhere"],
      },
      {
        group: "pov",
        terms: ["pov", "when", "that moment", "me when", "my face when"],
      },
      {
        group: "internet",
        terms: ["internet", "online", "web", "digital", "cyber", "virtual"],
      },
    ],
  },

  sfx: {
    primary: [
      // Sound Categories
      "sound",
      "audio",
      "sfx",
      "effect",
      "effects",
      "noise",
      "tone",
      "sample",
      "clip",
      "loop",

      // Impact & Hit Sounds
      "impact",
      "hit",
      "punch",
      "kick",
      "slam",
      "crash",
      "smash",
      "bang",
      "boom",
      "thud",
      "thump",
      "whoosh",
      "swoosh",
      "swish",
      "whip",
      "crack",
      "snap",
      "pop",
      "click",
      "clack",
      "tap",

      // Transition Sounds
      "transition",
      "swoosh",
      "whoosh",
      "swipe",
      "slide",
      "glitch",
      "static",
      "noise",
      "distortion",
      "reverse",
      "rewind",
      "fast forward",
      "speed up",
      "slow down",
      "riser",
      "drop",
      "build up",

      // UI & Interface
      "ui",
      "interface",
      "button",
      "click",
      "tap",
      "notification",
      "alert",
      "beep",
      "boop",
      "blip",
      "ding",
      "chime",
      "bell",
      "ping",
      "error",
      "success",
      "confirm",
      "cancel",
      "select",
      "hover",

      // Nature & Ambient
      "nature",
      "ambient",
      "atmosphere",
      "wind",
      "rain",
      "thunder",
      "storm",
      "water",
      "ocean",
      "wave",
      "fire",
      "flame",
      "crackle",
      "forest",
      "birds",
      "animals",
      "wildlife",
      "outdoor",
      "environment",

      // Music Elements
      "bass",
      "drum",
      "kick",
      "snare",
      "hi hat",
      "cymbal",
      "clap",
      "snap",
      "808",
      "sub",
      "drop",
      "beat",
      "rhythm",
      "melody",
      "chord",
      "note",
      "synth",
      "pad",
      "lead",
      "arp",
      "sequence",

      // Voice & Vocal
      "voice",
      "vocal",
      "speech",
      "talk",
      "speak",
      "say",
      "shout",
      "scream",
      "whisper",
      "laugh",
      "cry",
      "sigh",
      "breath",
      "gasp",
      "grunt",
      "moan",
      "groan",
      "cough",
      "sneeze",
      "yawn",

      // Technology & Sci-Fi
      "tech",
      "technology",
      "digital",
      "electronic",
      "cyber",
      "robot",
      "robotic",
      "mechanical",
      "machine",
      "computer",
      "glitch",
      "error",
      "processing",
      "loading",
      "scanning",
      "beep",
      "boop",
      "laser",
      "zap",
      "electric",
      "shock",
      "power",
      "energy",
      "futuristic",
      "sci fi",
      "space",
      "alien",
    ],
    subtopics: [
      {
        name: "Cinematic SFX",
        keywords: [
          "cinematic",
          "epic",
          "dramatic",
          "trailer",
          "film",
          "movie",
          "hollywood",
          "blockbuster",
          "orchestral",
          "score",
          "soundtrack",
          "tension",
          "suspense",
          "build",
          "climax",
          "resolution",
          "riser",
          "impact",
          "boom",
          "braaam",
          "horn",
          "drum hit",
          "percussion",
        ],
      },
      {
        name: "Gaming SFX",
        keywords: [
          "game",
          "gaming",
          "video game",
          "arcade",
          "retro",
          "8bit",
          "16bit",
          "pixel",
          "chiptune",
          "power up",
          "level up",
          "coin",
          "collect",
          "pickup",
          "jump",
          "shoot",
          "explosion",
          "damage",
          "health",
          "shield",
          "weapon",
          "reload",
          "footstep",
          "door",
          "chest",
          "inventory",
        ],
      },
      {
        name: "Social Media SFX",
        keywords: [
          "social",
          "media",
          "tiktok",
          "instagram",
          "youtube",
          "viral",
          "trending",
          "meme",
          "funny",
          "comedy",
          "transition",
          "zoom",
          "pan",
          "cut",
          "edit",
          "montage",
          "vlog",
          "podcast",
          "intro",
          "outro",
          "subscribe",
          "like",
          "comment",
          "share",
          "notification",
        ],
      },
      {
        name: "Horror SFX",
        keywords: [
          "horror",
          "scary",
          "creepy",
          "spooky",
          "eerie",
          "haunted",
          "ghost",
          "demon",
          "monster",
          "scream",
          "shriek",
          "whisper",
          "breath",
          "heartbeat",
          "tension",
          "suspense",
          "jumpscare",
          "door creak",
          "footsteps",
          "wind",
          "thunder",
          "rain",
          "darkness",
          "shadow",
        ],
      },
    ],
    synonyms: [
      {
        group: "sound",
        terms: ["sound", "audio", "sfx", "effect", "noise", "tone", "sample"],
      },
      {
        group: "impact",
        terms: ["impact", "hit", "punch", "slam", "crash", "bang", "boom", "thud"],
      },
      {
        group: "transition",
        terms: ["transition", "swoosh", "whoosh", "swipe", "slide", "cut"],
      },
      {
        group: "glitch",
        terms: ["glitch", "error", "distortion", "static", "noise", "corrupt"],
      },
      {
        group: "ui",
        terms: ["ui", "interface", "button", "click", "tap", "select"],
      },
      {
        group: "notification",
        terms: ["notification", "alert", "ping", "ding", "chime", "bell"],
      },
      {
        group: "bass",
        terms: ["bass", "sub", "low end", "808", "kick", "thump"],
      },
      {
        group: "drum",
        terms: ["drum", "percussion", "beat", "rhythm", "hit", "strike"],
      },
      {
        group: "cinematic",
        terms: ["cinematic", "epic", "dramatic", "trailer", "film", "movie"],
      },
      {
        group: "ambient",
        terms: ["ambient", "atmosphere", "background", "texture", "pad", "drone"],
      },
    ],
  },

  voiceover: {
    primary: [
      // Voice Types
      "voice",
      "voiceover",
      "vo",
      "narration",
      "narrator",
      "speech",
      "spoken",
      "talk",
      "dialogue",
      "monologue",
      "commentary",
      "announcement",
      "presentation",
      "lecture",
      "explanation",

      // AI & Technology
      "ai",
      "artificial intelligence",
      "robot",
      "robotic",
      "synthetic",
      "generated",
      "text to speech",
      "tts",
      "neural",
      "deep learning",
      "machine learning",
      "automated",
      "computer",
      "digital",

      // Voice Characteristics
      "male",
      "female",
      "man",
      "woman",
      "boy",
      "girl",
      "child",
      "adult",
      "young",
      "old",
      "elderly",
      "deep",
      "high",
      "low",
      "soft",
      "loud",
      "clear",
      "smooth",
      "rough",
      "raspy",
      "crisp",
      "warm",
      "cold",
      "friendly",
      "professional",
      "casual",
      "formal",
      "serious",
      "playful",

      // Accents & Languages
      "american",
      "british",
      "australian",
      "canadian",
      "english",
      "accent",
      "dialect",
      "language",
      "spanish",
      "french",
      "german",
      "italian",
      "japanese",
      "chinese",
      "korean",
      "hindi",
      "arabic",
      "multilingual",
      "bilingual",
      "native",
      "foreign",
      "international",
      "global",

      // Content Types
      "commercial",
      "ad",
      "advertisement",
      "promo",
      "promotional",
      "marketing",
      "sales",
      "pitch",
      "explainer",
      "tutorial",
      "guide",
      "how to",
      "instruction",
      "educational",
      "training",
      "course",
      "documentary",
      "story",
      "storytelling",
      "narrative",
      "audiobook",
      "podcast",
      "radio",
      "broadcast",

      // Emotions & Tones
      "happy",
      "sad",
      "angry",
      "excited",
      "calm",
      "energetic",
      "enthusiastic",
      "confident",
      "nervous",
      "serious",
      "funny",
      "humorous",
      "dramatic",
      "emotional",
      "passionate",
      "inspiring",
      "motivational",
      "soothing",
      "relaxing",
      "aggressive",
      "intense",
      "gentle",
      "kind",
      "harsh",
      "stern",
    ],
    subtopics: [
      {
        name: "Commercial VO",
        keywords: [
          "commercial",
          "ad",
          "advertisement",
          "promo",
          "promotional",
          "marketing",
          "brand",
          "product",
          "service",
          "company",
          "business",
          "corporate",
          "sales",
          "pitch",
          "offer",
          "deal",
          "discount",
          "limited time",
          "call to action",
          "cta",
          "buy now",
          "shop",
          "order",
          "subscribe",
        ],
      },
      {
        name: "Educational VO",
        keywords: [
          "educational",
          "education",
          "learning",
          "teach",
          "teaching",
          "lesson",
          "course",
          "training",
          "tutorial",
          "guide",
          "how to",
          "instruction",
          "explainer",
          "demonstration",
          "walkthrough",
          "step by step",
          "beginner",
          "advanced",
          "expert",
          "knowledge",
          "information",
          "facts",
        ],
      },
      {
        name: "Character Voices",
        keywords: [
          "character",
          "cartoon",
          "animation",
          "animated",
          "game",
          "gaming",
          "video game",
          "rpg",
          "fantasy",
          "sci fi",
          "hero",
          "villain",
          "monster",
          "creature",
          "alien",
          "robot",
          "animal",
          "impression",
          "impersonation",
          "mimic",
          "accent",
          "dialect",
          "personality",
          "quirky",
        ],
      },
      {
        name: "Documentary VO",
        keywords: [
          "documentary",
          "narration",
          "narrator",
          "storytelling",
          "story",
          "narrative",
          "history",
          "historical",
          "nature",
          "wildlife",
          "science",
          "discovery",
          "exploration",
          "investigation",
          "journalism",
          "news",
          "report",
          "documentary style",
          "authoritative",
          "informative",
        ],
      },
    ],
    synonyms: [
      {
        group: "voiceover",
        terms: ["voiceover", "voice over", "vo", "narration", "voice acting", "voice work"],
      },
      {
        group: "ai_voice",
        terms: ["ai voice", "artificial voice", "synthetic voice", "generated voice", "tts", "text to speech"],
      },
      {
        group: "narrator",
        terms: ["narrator", "voice actor", "voice talent", "speaker", "announcer"],
      },
      {
        group: "commercial",
        terms: ["commercial", "ad", "advertisement", "promo", "promotional", "marketing"],
      },
      {
        group: "explainer",
        terms: ["explainer", "tutorial", "guide", "how to", "instruction", "walkthrough"],
      },
      {
        group: "professional",
        terms: ["professional", "corporate", "business", "formal", "polished", "quality"],
      },
      {
        group: "friendly",
        terms: ["friendly", "warm", "welcoming", "approachable", "conversational", "casual"],
      },
      {
        group: "energetic",
        terms: ["energetic", "enthusiastic", "excited", "upbeat", "lively", "dynamic"],
      },
      {
        group: "calm",
        terms: ["calm", "soothing", "relaxing", "peaceful", "tranquil", "gentle"],
      },
      {
        group: "dramatic",
        terms: ["dramatic", "intense", "powerful", "emotional", "passionate", "compelling"],
      },
    ],
  },

  ebook: {
    primary: [
      // Book Types
      "ebook",
      "book",
      "guide",
      "manual",
      "handbook",
      "workbook",
      "journal",
      "planner",
      "template",
      "checklist",
      "worksheet",
      "resource",
      "toolkit",
      "blueprint",
      "framework",
      "system",

      // Business & Marketing
      "business",
      "marketing",
      "sales",
      "entrepreneur",
      "startup",
      "growth",
      "strategy",
      "plan",
      "funnel",
      "conversion",
      "lead",
      "customer",
      "client",
      "revenue",
      "profit",
      "income",
      "money",
      "branding",
      "brand",
      "social media",
      "content",
      "seo",
      "advertising",
      "copywriting",
      "email",

      // Self-Help & Personal Development
      "self help",
      "personal development",
      "self improvement",
      "growth",
      "mindset",
      "habits",
      "routine",
      "productivity",
      "time management",
      "goal setting",
      "success",
      "achievement",
      "motivation",
      "confidence",
      "mindfulness",
      "meditation",
      "wellness",
      "health",
      "fitness",
      "lifestyle",

      // Finance & Wealth
      "finance",
      "financial",
      "money",
      "wealth",
      "investing",
      "investment",
      "stocks",
      "crypto",
      "real estate",
      "passive income",
      "side hustle",
      "budget",
      "budgeting",
      "saving",
      "debt",
      "credit",
      "retirement",
      "financial freedom",
      "millionaire",
      "rich",
      "wealthy",

      // Skills & Learning
      "learn",
      "learning",
      "skill",
      "skills",
      "training",
      "course",
      "lesson",
      "tutorial",
      "guide",
      "how to",
      "step by step",
      "beginner",
      "advanced",
      "master",
      "mastery",
      "expert",
      "professional",
      "certification",
      "diploma",
      "education",
      "knowledge",
      "wisdom",
      "technique",
      "method",
      "strategy",

      // Niches
      "fitness",
      "health",
      "nutrition",
      "diet",
      "weight loss",
      "muscle",
      "workout",
      "exercise",
      "relationship",
      "dating",
      "love",
      "marriage",
      "parenting",
      "family",
      "kids",
      "children",
      "career",
      "job",
      "resume",
      "interview",
      "promotion",
      "leadership",
      "management",
      "team",
      "creative",
      "art",
      "design",
      "writing",
      "photography",
      "music",
      "craft",
      "hobby",
    ],
    subtopics: [
      {
        name: "Business Ebooks",
        keywords: [
          "business plan",
          "business model",
          "startup guide",
          "entrepreneur guide",
          "marketing strategy",
          "sales funnel",
          "lead generation",
          "customer acquisition",
          "growth hacking",
          "scaling",
          "business growth",
          "revenue growth",
          "profit maximization",
          "business success",
          "case study",
          "business template",
          "business framework",
          "business system",
          "business blueprint",
        ],
      },
      {
        name: "Self-Help Ebooks",
        keywords: [
          "self help guide",
          "personal growth",
          "self improvement guide",
          "habit building",
          "morning routine",
          "productivity system",
          "time management guide",
          "goal achievement",
          "success principles",
          "mindset shift",
          "positive thinking",
          "confidence building",
          "overcome fear",
          "anxiety relief",
          "stress management",
          "mental health",
          "emotional intelligence",
          "life transformation",
        ],
      },
      {
        name: "How-To Guides",
        keywords: [
          "how to guide",
          "step by step guide",
          "complete guide",
          "ultimate guide",
          "beginner guide",
          "quick start guide",
          "getting started",
          "tutorial guide",
          "instruction manual",
          "handbook",
          "practical guide",
          "actionable guide",
          "proven method",
          "simple system",
          "easy way",
        ],
      },
      {
        name: "Templates & Workbooks",
        keywords: [
          "template",
          "workbook",
          "worksheet",
          "planner",
          "journal",
          "tracker",
          "checklist",
          "toolkit",
          "resource pack",
          "bundle",
          "collection",
          "library",
          "swipe file",
          "done for you",
          "dfy",
          "plug and play",
          "ready to use",
          "customizable",
          "editable",
          "fillable",
          "printable",
        ],
      },
    ],
    synonyms: [
      {
        group: "ebook",
        terms: ["ebook", "e-book", "digital book", "pdf", "guide", "manual", "handbook"],
      },
      {
        group: "guide",
        terms: ["guide", "manual", "handbook", "tutorial", "how to", "walkthrough"],
      },
      {
        group: "business",
        terms: ["business", "entrepreneur", "startup", "company", "enterprise", "venture"],
      },
      {
        group: "marketing",
        terms: ["marketing", "promotion", "advertising", "branding", "growth", "sales"],
      },
      {
        group: "self_help",
        terms: ["self help", "self improvement", "personal development", "growth", "transformation"],
      },
      {
        group: "success",
        terms: ["success", "achievement", "accomplishment", "winning", "mastery", "excellence"],
      },
      {
        group: "wealth",
        terms: ["wealth", "money", "financial freedom", "rich", "millionaire", "prosperity"],
      },
      {
        group: "productivity",
        terms: ["productivity", "efficiency", "time management", "organization", "optimization"],
      },
      {
        group: "template",
        terms: ["template", "workbook", "worksheet", "planner", "toolkit", "resource"],
      },
      {
        group: "beginner",
        terms: ["beginner", "starter", "newbie", "getting started", "introduction", "basics"],
      },
    ],
  },

  broll: {
    primary: [
      // General B-roll Terms
      "broll",
      "b-roll",
      "b roll",
      "footage",
      "stock footage",
      "cinematic",
      "establishing shot",
      "cutaway",
      "insert shot",
      "supplemental footage",
      "visual",
      "scene",
      "shot",
      "clip",
      "sequence",

      // Camera Movements
      "pan",
      "tilt",
      "zoom",
      "dolly",
      "tracking",
      "crane",
      "drone",
      "aerial",
      "flyover",
      "orbit",
      "reveal",
      "push in",
      "pull out",
      "handheld",
      "steadicam",
      "gimbal",
      "slider",
      "timelapse",
      "hyperlapse",
      "slow motion",
      "slowmo",

      // Urban & City
      "city",
      "urban",
      "cityscape",
      "skyline",
      "downtown",
      "street",
      "traffic",
      "cars",
      "buildings",
      "architecture",
      "skyscraper",
      "metro",
      "subway",
      "pedestrian",
      "crosswalk",
      "intersection",
      "night lights",
      "neon",
      "billboard",
      "storefront",

      // Nature & Outdoor
      "nature",
      "landscape",
      "mountain",
      "forest",
      "trees",
      "woods",
      "river",
      "lake",
      "ocean",
      "beach",
      "waves",
      "sunset",
      "sunrise",
      "sky",
      "clouds",
      "weather",
      "rain",
      "snow",
      "fog",
      "mist",
      "waterfall",
      "canyon",
      "desert",
      "field",
      "meadow",
      "flowers",
      "wildlife",
      "birds",
      "animals",

      // Workspace & Business
      "workspace",
      "office",
      "desk",
      "computer",
      "laptop",
      "keyboard",
      "typing",
      "mouse",
      "monitor",
      "screen",
      "meeting",
      "conference",
      "presentation",
      "whiteboard",
      "notes",
      "writing",
      "notebook",
      "pen",
      "paper",
      "documents",
      "business",
      "corporate",
      "professional",
      "work",
      "working",

      // Lifestyle & People
      "lifestyle",
      "people",
      "person",
      "hands",
      "walking",
      "running",
      "sitting",
      "standing",
      "talking",
      "laughing",
      "smiling",
      "thinking",
      "reading",
      "studying",
      "learning",
      "creating",
      "making",
      "building",
      "cooking",
      "eating",
      "drinking",
      "coffee",
      "tea",
      "food",
      "meal",

      // Technology & Modern
      "technology",
      "tech",
      "digital",
      "modern",
      "innovation",
      "device",
      "smartphone",
      "phone",
      "tablet",
      "gadget",
      "screen",
      "display",
      "interface",
      "app",
      "software",
      "code",
      "coding",
      "programming",
      "data",
      "network",
      "connection",
      "wifi",
      "internet",

      // Creative & Artistic
      "creative",
      "art",
      "artistic",
      "design",
      "designer",
      "drawing",
      "painting",
      "sketch",
      "illustration",
      "photography",
      "camera",
      "lens",
      "studio",
      "lighting",
      "setup",
      "equipment",
      "gear",
      "production",
      "filming",
      "shooting",
      "recording",

      // Fitness & Health
      "fitness",
      "gym",
      "workout",
      "exercise",
      "training",
      "running",
      "jogging",
      "yoga",
      "stretching",
      "weights",
      "dumbbell",
      "barbell",
      "equipment",
      "health",
      "wellness",
      "active",
      "sport",
      "sports",
      "athlete",
      "athletic",
    ],
    subtopics: [
      {
        name: "Urban B-roll",
        keywords: [
          "city life",
          "urban environment",
          "street scene",
          "traffic flow",
          "busy street",
          "pedestrians walking",
          "city lights",
          "night city",
          "downtown area",
          "metropolitan",
          "urban landscape",
          "city architecture",
          "modern buildings",
          "glass buildings",
          "reflections",
          "city movement",
          "rush hour",
          "commute",
          "public transport",
          "subway station",
        ],
      },
      {
        name: "Nature B-roll",
        keywords: [
          "natural landscape",
          "scenic view",
          "mountain range",
          "forest path",
          "tree canopy",
          "flowing water",
          "ocean waves",
          "beach scene",
          "sunset view",
          "golden hour",
          "blue hour",
          "dramatic sky",
          "cloud movement",
          "weather patterns",
          "seasonal change",
          "wildlife habitat",
          "natural beauty",
          "peaceful nature",
          "serene landscape",
          "outdoor scenery",
        ],
      },
      {
        name: "Workspace B-roll",
        keywords: [
          "office environment",
          "desk setup",
          "work station",
          "computer work",
          "typing hands",
          "keyboard closeup",
          "screen display",
          "office supplies",
          "notepad writing",
          "pen and paper",
          "coffee on desk",
          "workspace organization",
          "professional setting",
          "business environment",
          "meeting room",
          "conference table",
          "presentation screen",
          "collaborative work",
          "team meeting",
          "office culture",
        ],
      },
      {
        name: "Lifestyle B-roll",
        keywords: [
          "daily life",
          "everyday moments",
          "morning routine",
          "coffee making",
          "breakfast prep",
          "getting ready",
          "commuting",
          "shopping",
          "cooking food",
          "meal preparation",
          "eating together",
          "social gathering",
          "friends hanging out",
          "family time",
          "leisure activity",
          "hobby pursuit",
          "relaxation",
          "self care",
          "personal time",
          "lifestyle choice",
        ],
      },
      {
        name: "Detail Shots",
        keywords: [
          "close up",
          "macro shot",
          "detail focus",
          "texture closeup",
          "hands working",
          "finger movement",
          "product detail",
          "material texture",
          "surface detail",
          "intricate detail",
          "fine detail",
          "shallow depth",
          "bokeh background",
          "selective focus",
          "sharp detail",
          "crisp focus",
          "intimate shot",
          "personal detail",
          "small object",
          "precise movement",
        ],
      },
    ],
    synonyms: [
      {
        group: "broll",
        terms: ["b-roll", "b roll", "broll", "supplemental footage", "cutaway", "insert shot"],
      },
      {
        group: "cinematic",
        terms: ["cinematic", "filmic", "movie-like", "professional footage", "high quality"],
      },
      {
        group: "aerial",
        terms: ["aerial", "drone", "flyover", "bird's eye", "overhead", "from above"],
      },
      {
        group: "timelapse",
        terms: ["timelapse", "time lapse", "hyperlapse", "fast motion", "sped up"],
      },
      {
        group: "slowmo",
        terms: ["slow motion", "slowmo", "slow-mo", "slowed down", "high speed"],
      },
      {
        group: "urban",
        terms: ["urban", "city", "metropolitan", "downtown", "cityscape"],
      },
      {
        group: "nature",
        terms: ["nature", "natural", "outdoor", "landscape", "scenic"],
      },
      {
        group: "workspace",
        terms: ["workspace", "office", "desk", "work station", "professional setting"],
      },
      {
        group: "lifestyle",
        terms: ["lifestyle", "daily life", "everyday", "routine", "living"],
      },
      {
        group: "detail",
        terms: ["detail", "close up", "closeup", "macro", "intimate shot"],
      },
    ],
  },

  background_videos: {
    primary: [
      // General Background Terms
      "background",
      "backdrop",
      "overlay",
      "loop",
      "looping",
      "seamless",
      "continuous",
      "repeating",
      "animated background",
      "motion background",
      "video background",
      "moving background",
      "dynamic background",
      "live background",

      // Abstract & Patterns
      "abstract",
      "pattern",
      "geometric",
      "shapes",
      "lines",
      "curves",
      "waves",
      "circles",
      "squares",
      "triangles",
      "hexagon",
      "polygon",
      "fractal",
      "kaleidoscope",
      "symmetry",
      "tessellation",
      "grid",
      "mesh",
      "network",
      "web",
      "matrix",

      // Colors & Gradients
      "gradient",
      "color",
      "colorful",
      "vibrant",
      "bright",
      "dark",
      "light",
      "neon",
      "glow",
      "luminous",
      "radiant",
      "iridescent",
      "holographic",
      "rainbow",
      "multicolor",
      "monochrome",
      "black and white",
      "grayscale",
      "pastel",
      "saturated",
      "desaturated",

      // Motion & Animation
      "motion",
      "movement",
      "animated",
      "animation",
      "flowing",
      "floating",
      "drifting",
      "rotating",
      "spinning",
      "swirling",
      "pulsing",
      "pulsating",
      "breathing",
      "oscillating",
      "undulating",
      "rippling",
      "waving",
      "morphing",
      "transforming",
      "evolving",
      "shifting",
      "transitioning",

      // Particles & Effects
      "particles",
      "particle system",
      "dots",
      "points",
      "sparkles",
      "glitter",
      "stars",
      "dust",
      "smoke",
      "fog",
      "mist",
      "haze",
      "vapor",
      "clouds",
      "bubbles",
      "orbs",
      "spheres",
      "bokeh",
      "blur",
      "defocus",
      "soft focus",

      // Technology & Digital
      "digital",
      "tech",
      "technology",
      "futuristic",
      "sci-fi",
      "cyber",
      "cyberpunk",
      "circuit",
      "circuit board",
      "binary",
      "code",
      "data",
      "information",
      "network",
      "connection",
      "nodes",
      "lines connecting",
      "plexus",
      "wireframe",
      "hologram",
      "projection",
      "screen",
      "display",
      "interface",
      "hud",
      "heads up display",

      // Nature & Organic
      "nature",
      "natural",
      "organic",
      "fluid",
      "liquid",
      "water",
      "ocean",
      "waves",
      "ripples",
      "flow",
      "stream",
      "current",
      "fire",
      "flames",
      "burning",
      "smoke",
      "plasma",
      "energy",
      "aurora",
      "northern lights",
      "cosmic",
      "space",
      "galaxy",
      "nebula",
      "stars",
      "universe",

      // Textures & Materials
      "texture",
      "material",
      "surface",
      "fabric",
      "cloth",
      "silk",
      "satin",
      "velvet",
      "metal",
      "metallic",
      "chrome",
      "gold",
      "silver",
      "copper",
      "bronze",
      "glass",
      "crystal",
      "diamond",
      "gem",
      "stone",
      "marble",
      "granite",
      "wood",
      "paper",
      "canvas",

      // Lighting & Atmosphere
      "lighting",
      "light",
      "lights",
      "illumination",
      "glow",
      "shine",
      "shimmer",
      "glimmer",
      "sparkle",
      "twinkle",
      "flare",
      "lens flare",
      "rays",
      "beams",
      "spotlight",
      "ambient light",
      "mood lighting",
      "atmospheric",
      "atmosphere",
      "ambience",
      "environment",
      "setting",

      // Styles & Aesthetics
      "minimal",
      "minimalist",
      "simple",
      "clean",
      "elegant",
      "sophisticated",
      "modern",
      "contemporary",
      "retro",
      "vintage",
      "classic",
      "timeless",
      "artistic",
      "creative",
      "unique",
      "original",
      "custom",
      "professional",
      "premium",
      "luxury",
      "high end",
    ],
    subtopics: [
      {
        name: "Abstract Backgrounds",
        keywords: [
          "abstract art",
          "abstract motion",
          "abstract shapes",
          "abstract patterns",
          "geometric abstract",
          "fluid abstract",
          "organic abstract",
          "colorful abstract",
          "minimal abstract",
          "modern abstract",
          "dynamic abstract",
          "flowing abstract",
          "morphing shapes",
          "transforming patterns",
          "evolving design",
          "generative art",
          "procedural animation",
          "algorithmic design",
          "mathematical patterns",
          "fractal animation",
        ],
      },
      {
        name: "Particle Backgrounds",
        keywords: [
          "particle animation",
          "particle flow",
          "particle system",
          "floating particles",
          "drifting particles",
          "connected particles",
          "particle network",
          "particle field",
          "particle cloud",
          "particle stream",
          "glowing particles",
          "luminous particles",
          "sparkle particles",
          "dust particles",
          "snow particles",
          "rain particles",
          "bubble particles",
          "sphere particles",
          "dot particles",
          "point particles",
        ],
      },
      {
        name: "Gradient Backgrounds",
        keywords: [
          "gradient motion",
          "gradient flow",
          "gradient animation",
          "color gradient",
          "smooth gradient",
          "soft gradient",
          "vibrant gradient",
          "pastel gradient",
          "neon gradient",
          "rainbow gradient",
          "multicolor gradient",
          "shifting gradient",
          "morphing gradient",
          "transitioning colors",
          "color blend",
          "color mix",
          "color fade",
          "color sweep",
          "color wave",
          "gradient overlay",
        ],
      },
      {
        name: "Tech Backgrounds",
        keywords: [
          "tech background",
          "digital background",
          "futuristic background",
          "cyber background",
          "circuit background",
          "matrix background",
          "code background",
          "data visualization",
          "network visualization",
          "connection lines",
          "plexus effect",
          "wireframe animation",
          "holographic effect",
          "hud interface",
          "sci-fi interface",
          "tech grid",
          "digital grid",
          "binary code",
          "data stream",
          "information flow",
        ],
      },
      {
        name: "Nature Backgrounds",
        keywords: [
          "nature background",
          "organic background",
          "water background",
          "ocean background",
          "wave background",
          "ripple effect",
          "fluid motion",
          "liquid animation",
          "fire background",
          "flame animation",
          "smoke background",
          "fog background",
          "cloud background",
          "sky background",
          "aurora background",
          "space background",
          "galaxy background",
          "nebula background",
          "cosmic background",
          "universe background",
        ],
      },
      {
        name: "Minimal Backgrounds",
        keywords: [
          "minimal background",
          "minimalist background",
          "simple background",
          "clean background",
          "subtle background",
          "soft background",
          "gentle motion",
          "slow movement",
          "calm animation",
          "peaceful background",
          "serene background",
          "elegant background",
          "sophisticated background",
          "professional background",
          "corporate background",
          "business background",
          "neutral background",
          "understated background",
          "refined background",
          "tasteful background",
        ],
      },
    ],
    synonyms: [
      {
        group: "background",
        terms: ["background", "backdrop", "bg", "video background", "animated background"],
      },
      {
        group: "loop",
        terms: ["loop", "looping", "seamless loop", "continuous", "repeating", "endless"],
      },
      {
        group: "abstract",
        terms: ["abstract", "non-representational", "conceptual", "artistic", "creative"],
      },
      {
        group: "gradient",
        terms: ["gradient", "color blend", "color transition", "color fade", "ombre"],
      },
      {
        group: "particles",
        terms: ["particles", "particle system", "dots", "points", "elements"],
      },
      {
        group: "motion",
        terms: ["motion", "movement", "animation", "animated", "moving", "dynamic"],
      },
      {
        group: "tech",
        terms: ["tech", "technology", "digital", "futuristic", "cyber", "sci-fi"],
      },
      {
        group: "glow",
        terms: ["glow", "glowing", "luminous", "radiant", "shining", "bright"],
      },
      {
        group: "minimal",
        terms: ["minimal", "minimalist", "simple", "clean", "subtle", "understated"],
      },
      {
        group: "fluid",
        terms: ["fluid", "liquid", "flowing", "smooth", "organic", "natural"],
      },
    ],
  },
}
